### ISSUE TITLE
Source of User Manual

### ISSUE THREAD

**Issue by Samehadar** [Darkpingouin/todolist#1]
Good day! Nice to talk with you.

I want to fork your app and rewrite UI and add more functions which I need.
Can you add to the repository source of your User Manual pdf file? 

Thank you!

**Comment by Darkpingouin** [comment]
Hello,

I am affraid I don't have anymore as it was just for a school project. 
The powerpoint presentation template I used to create the user manual is available here : https://www.slidescarnival.com/arvirargus-free-presentation-template/1094 
If you feel like using the same as I did. 
I am really sorry that I don't have anymore.

Can't wait to see how you will improve my project 😄

**Comment by Samehadar** [comment]
I need it for a uni project too :)

Thanks for this template. Can you give me your contacts to answer questions, if they come from me? Or find me on any social network by nickname @samehadar 
I think that find your twitter (/Darkpingouin) account, but I'm not sure :)
